config/routes.rb
MotoDynasty::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  root 'home#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users, only: [:show] do 
    collection { post :sort_rider }
  end
  
  resources :series

  resources :rounds, only: [:show,:index] do
    resources :licenses, only: [:new, :create, :update, :destroy]
  end

  resources :race_classes, only: [:show] do
    resources :licenses, only: [:new, :create, :update, :destroy]
  end

  resources :user_round_bonus_selections, only: [:create, :update, :destroy]

  resources :teams

  resources :rider_positions, only: [:create, :update, :destroy]

  resources :user_messages, only: [:new, :create]

  resources :custom_series_licenses, only: [:create, :destroy] do
    collection do 
      get :join
      post :accept_request
      delete :leave_custom_series
    end
  end

  resources :custom_series_invitations, only: [:create, :destroy]
  resources :custom_series_requests, only: [:create, :destroy]

  resources :custom_series do
    get :show_request    
    collection do
      get 'new_public'
      get 'new_private'
      post 'search'
    end
  end


  post '/update-with-last-week-riders', to: 'rider_positions#update_with_lastweek_riders', as: 'update_with_lastweek_riders'
  get '/instructions', to: 'home#instructions'  
  get '/series-invitation/:series_id', to: 'custom_series_invitations#new', as: 'new_series_invitation'
  # /leaderboards(/series/:series_id(/race_classes/:race_class_id(/rounds/:round_id)))
  get '/leaderboards', to: 'leaderboards/base#show', as: 'leaderboards'

  get '/manage_rounds', to: 'rounds#manage_rounds'


  namespace :leaderboards do
    resources :series, only: [:show] do
      resources :race_classes, only: [:show] do
        resources :rounds, only: [:show]
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :rider_positions, dependent: :destroy
  has_many :payments
  has_many :series_licenses, dependent: :destroy
  has_many :series, through: :series_licenses
  has_many :points, as: :pointable, dependent: :destroy
  has_many :user_round_bonus_selections, dependent: :destroy
  has_many :user_round_stats, dependent: :destroy
  has_many :owned_series, class_name: 'CustomSeries', dependent: :destroy
  
  has_many :custom_series_licenses, dependent: :destroy
  has_many :custom_series, through: :custom_series_licenses

  has_many :licenses, dependent: :destroy

  def handle
    return email if username.blank?
    username
  end

  def remove_credits(amount)
    if self.credits >= amount
      self.credits -= amount
      self.save
    else
      raise "Not enough credits"
    end
  end

  def available_rider_position_for_round(round)
    #Change value to control the number of riders selected in each round.
    if rider_positions.where(round: round).count < 22
      rider_positions.new(round: round)
    else
      rider_positions.find_by(round: round, rider_id: nil)
    end
  end

  def available_riders_for_round(round)
    begin
      existing_riders = rider_positions.where(round: round).collect(&:rider).compact
      round.riders - existing_riders
    rescue
      {}
    end
  end

  def rider_positions_for_round(round)
    rider_positions.where(round: round).order('position ASC')
  end

  def order_riders_for_round(round)
    rider_positions.where(round: round).order('position').collect(&:rider)
  end

  def total_points
    user_round_stats.sum('total')
  end

  def total_points_for_round(round)
    rider_positions.where(round: round).to_a.sum(&:score)
  end

  def total_points_for_race_class(race_class)
    total_points = 0
    race_class.rounds.each do |round|
      total_points += total_points_for_round(round)
    end
    total_points
  end

  def bonus_selection_by_round_and_type(round, type)
    bonus_type = BonusType.find_by(name: type)
    user_round_bonus_selections.find_by(round_id: round.id, bonus_type_id: bonus_type.id)
  end

  def bonus_selection_available?(round, bonus_type)
    round.bonus_selection_open?(bonus_type)
  end

  def custom_series_ids(series)
    custom_series.where(series: series).collect(&:id)
  end

  def custom_series_for_series(series)
    custom_series.where(series: series)
  end

  def participant_in_round?(round)
    rider_positions_for_round(round).any?
  end

  def after_sign_in_path
    pending_invitations = CustomSeriesInvitation.where(recipient_email: email).order(created_at: :desc)
    if pending_invitations.empty?
      Rails.application.routes.url_helpers.user_path self
    else
      latest_invitation = pending_invitations.first
      Rails.application.routes.url_helpers.custom_series_path(latest_invitation.custom_series,
                                                              token: latest_invitation.token)
    end
  end

  def get_custom_series_invitations
    CustomSeriesInvitation.where(recipient_email: email).order(created_at: :desc)
  end

  def get_custom_series_requests
    #custom_series.map(&:custom_series_requests)
    requests = []
    custom_series.map{ |custom_series| requests = requests | custom_series.custom_series_requests }
    requests
  end

  def race_classes    
    licenses.map(&:race_class).uniq    
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :facebook_id => auth.uid).first
    puts '=== find_for_facebook_oauth ===', user.inspect
    if user && user.oauth_token.nil?
      user.update(oauth_token: auth.credentials.token, 
                  oauth_expires_at: Time.at(auth.credentials.expires_at))
    elsif !user
      puts '=== User ==='

      # user = User.create(name:auth.extra.raw_info.name,
      #                      provider:auth.provider,
      #                      facebook_id:auth.uid,
      #                      email:auth.info.email,
      #                      oauth_token: auth.credentials.token,
      #                      oauth_expires_at: Time.at(auth.credentials.expires_at),
      #                      password:Devise.friendly_token[0,20]
      #                      )
      puts auth.info.inspect
      user = User.find_by_email(auth.info.email)
      if !user
        user = User.new(name:auth.extra.raw_info.name,
                           provider:auth.provider,
                           facebook_id:auth.uid,
                           email:auth.info.email,
                           oauth_token: auth.credentials.token,
                           oauth_expires_at: Time.at(auth.credentials.expires_at),
                           password:Devise.friendly_token[0,20]
                           )
        if user.save
        else
          puts '==Error==', user.errors.full_messages
        end
      end

    end
    user
  end  
  def self.find_or_create_by_uid(uid, params)
    user = User.where(provider: 'facebook', facebook_id: uid.to_s).first
    unless user
      user = User.create(  name: params[:name],
                           provider: 'facebook',
                           facebook_id: facebook_id.to_s,
                           email: "#{facebook_id.to_s}@fb.com",
                           password: Devise.friendly_token[0,20]
                        )
    end
    user
  end   

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end  

  def facebook
    @facebook ||= Koala::Facebook::API.new(oauth_token)
    block_given? ? yield(@facebook) : @facebook
    rescue Koala::Facebook::APIError => e
      logger.info e.to_s
      nil # or consider a custom null object
  end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in @user, :event => :authentication      
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?      
      redirect_to :root
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except("extra")      
      redirect_to :root
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def show
  end

  def sort_rider
    round_id = params[:round_id]
    round = Round.find(round_id)
    if round.end_time > Time.now
      params[:sortable].each_with_index do |rider, index|
        rider_position_id = rider.gsub('rider_position_', '').to_i
        rider_position = RiderPosition.find(rider_position_id)
        rider_position.position = index+1
        rider_position.save if rider_position.changed?
      end
      render nothing: true
    else
      render nothing: true, status: 400
    end
  end
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def bonus_button_text(bonus_type)
    case bonus_type.name
      when "HoleShot"
        'Main Event Holeshot'
      else
        "#{bonus_type.to_s}"
    end    
  end
end

app/views/users/_finished_round.html.slim
.row
  h3.col-sm-10.col-md-6
    = round.name
  h3.col-md-6.visible-md.visible-lg
    |Race Finish
- stats = current_user.user_round_stats.where(round: round).first
- if stats.nil?

-else
  h5 
    |Points for round: &nbsp;
    = stats.total
  .row
    ol.col-sm-10.col-md-6.font-black
      -current_user.rider_positions_for_round(round).each do |rider_position|
        - if rider_position.try(:rider)
          li
            = rider_position.rider.name
            span
              |&nbsp;
              |points: 
              = rider_position.score
      h6 Bonus Selection

      p Pole Position Score
      p = stats.pole_position_score
      p Moto Winner Score
      p = stats.heat_winner_score
      p Main Event Hole Shot score
      p = stats.hole_shot_score
   
    -if round.finished?
      h3.col-md-6.visible-sm.visible-xs
        |Race Finish
      ol.col-sm-10.col-md-6.font-black
        -round.round_riders_where_finished_is(true).each do |round_rider|
          li
            = round_rider.finished_description
  

app/views/users/_race_class.html.slim
.panel.panel-default
  .panel-body
    h4.cardHeader
      |Race Class
      | &nbsp;
      = race_class.name
    - if race_class.registered_and_paid?(current_user)
      button class='btn btn-primary' disabled='disabled' Eligible for race class prize
    - elsif race_class.available_for_purchase?
      - if race_class.license_cost > 0
        = link_to "Upgrade to win race class prize (#{format_money race_class.license_cost})",
                        new_race_class_license_path(race_class),
                        class: 'btn btn-success'
    p
      |Total Points: &nbsp;
      = current_user.total_points_for_race_class(race_class)
      - if round = Round.current_for(race_class)
        h3
          = round.name
        - if round.registered? current_user
          - if round.registered_and_paid? current_user
            button class='btn btn-primary' disabled='disabled' Eligible for round prize
          - elsif round.available_for_purchase?
          = link_to "Upgrade to win round prize (#{format_money round.license_cost})",
                new_round_license_path(round),
                class: 'btn btn-success payButton'
          .row 
            .col-md-12
              p.timeTitle
                | Auto Submit : &nbsp;
              p.endTime
                = format_datetime(round.end_time)
              .clearfix
                - if round.rider_selection_open? 
                  = render partial: 'users/round', locals: {round: round, race_class: race_class} 
                - else
                  = render partial: 'users/started_round', locals: {round: round, race_class: race_class} 
        - else
          p Register for this round to play.
    h4 
      |Finished Rounds  
    ul.finished_rounds    
      - Round.finished_for(race_class).each do |round|
        li 
          = link_to round.name, round_path(round)

app/views/users/_round.html.slim
-if can? :edit, current_user          
  - rider_position = current_user.available_rider_position_for_round(round)
  -if rider_position.present?
    hr
    .row.seleteTitle
      .col-md-12
        |Select your riders
    .row
      .col-md-8.col-sm-12
        = form_for rider_position, remote: true, html: {class: 'form-inline'} do |f|
          = hidden_field_tag :div_id, "race_class#{race_class.id}"
          = f.hidden_field :round_id, value: round.id
          .row.racer-row
            .col-sm-7.col-xs-8 
              = f.collection_select :rider_id, current_user.available_riders_for_round(round), :id, :to_s, {}, {class: 'form-control'}
            .col-sm-2.col-xs-4
              = f.submit "Add Rider", class: "btn btn-primary", data: { disable_with: "Adding..." }

        = form_for rider_position, url: update_with_lastweek_riders_path, method: :post, remote: true, html: {class: 'form-inline'} do |f|
          = hidden_field_tag :div_id, "race_class#{race_class.id}"
          = f.hidden_field :round_id, value: round.id
          = f.submit "Regenerate", class: "btn btn-primary", data: { disable_with: "Regenerating..." }
  br
  .clearfix
    ol.select_riders.col-sm-12.col-md-12 data-update-url=(sort_rider_users_path) data-round-id=(round.id)
      - current_user.rider_positions_for_round(round).each_with_index do |rider_position, index|        
        = content_tag_for :li, rider_position do
          .row
            .col-xs-8          
              a.handle.btn-sm.move-btn href="#" onclick="event.preventDefault()" id=("rider_position_handle#{rider_position.id}")
                span.glyphicon.glyphicon-sort.glyph-white
              |&nbsp;              
              = rider_position.rider.try(:race_number)
              | &nbsp; - &nbsp;
              = rider_position.rider.try(:name)
            .col-xs-4.pull-right 
              -if rider_position.rider
                = link_to 'Remove', rider_position_path(rider_position, div_id: "race_class#{race_class.id}"), method: :delete, remote: true,  class: "btn btn-danger btn-xs pull-right", id: 'remove_rider_button'
  .row.seleteTitle
    h4.col-md-12
      |Bonus (Optional)
      span.glyphicon.glyphicon-question-sign.btn data-toggle="modal" data-target="#bonusModal"
  .row
    .col-md-12
      -BonusType.ordered.each do |bonus_type|
        - if selection = current_user.bonus_selection_by_round_and_type(round, bonus_type.name)
          .row.racer-row
            .col-md-4
              -if bonus_type.name == "HeatWinner"
                strong = "Moto Winner"
                |: &nbsp;
                = selection.try(:rider).try(:name)
              -else
                strong = bonus_type.to_s
                |: &nbsp;
                = selection.try(:rider).try(:name)
            .col-sm-5.col-xs-8
              -if current_user.bonus_selection_available?(round, bonus_type)
                = link_to content_tag(:button, "Remove", class: "btn btn-danger RemoveBonus"), user_round_bonus_selection_path(selection, race_class: race_class, div_id: "race_class#{race_class.id}"), method: :delete, remote: true
              -else
                p
                  strong
                    = bonus_type.to_s
                  |&nbsp; selection is currently closed
            .col-md-3
              b
                |+/- &nbsp;
                |points &nbsp;
                =bonus_type.value
        -else 
          -if current_user.bonus_selection_available?(round, bonus_type)
            -if bonus_type.name == "PolePosition"
              p Pole Position Selection Ends
              p = format_datetime(round.pole_position_end)
            = form_for current_user.user_round_bonus_selections.new, remote: true, html: {class: 'form-inline'} do |f|
              = hidden_field_tag :div_id, "race_class#{race_class.id}"
              = hidden_field_tag :race_class, race_class.id
              = f.hidden_field :round_id, value: round.id
              = f.hidden_field :bonus_type_id, value: bonus_type.id
              .row.racer-row
                -if bonus_type.name == "HeatWinner"
                  label.bonus.Blabel for='bonus'
                    |Moto Winner
                    |&nbsp;
                    b
                      |+/- &nbsp;
                      =bonus_type.value
                -else
                  label.bonus.Blabel for='bonus'
                    =bonus_type 
                    |&nbsp;
                    b
                      |+/- &nbsp;
                      =bonus_type.value
                .col-sm-5.col-xs-8
                  = f.collection_select :rider_id, round.riders, :id, :to_s, {}, {class: 'form-control bonus'}

                .col-md-2.col-sm-3.col-xs-4           
                  = submit_tag "Add", class: "btn btn-primary bonus add_bonus_#{bonus_type.name.downcase}", data: { disable_with: "Adding..." }
                
                  
                
          -else
            p
              strong
                = bonus_type.to_s
              |&nbsp; selection is currently closed
      
- else
  p
    | Rider selection is currently closed. 
            
            

app/views/users/_started_round.html.slim
h4.text-center.text-info
  |Round currently closed for selection
h5 Rider Selection
ol
  - current_user.rider_positions_for_round(round).each_with_index do |rider_position, index|
    = content_tag_for :li, rider_position do
      .row
        .col-sm-4
          = rider_position.rider.try(:race_number)
          | &nbsp; - &nbsp;
          = rider_position.rider.try(:name)
        .col-sm-8
h5 Bonus Selection
-BonusType.ordered.each do |bonus_type|
  - selection = current_user.bonus_selection_by_round_and_type(round, bonus_type.name)
  - if selection
    p= bonus_type.to_s
    p= selection.rider.to_s
  - else
    p
      |None selected for &nbsp;
      = bonus_type.to_s

app/views/users/show.html.slim
.row
  .col-md-12.col-sm-12.available
    h2.available Available Series 
    nav.nav.nav_horiz.nav_context
      ul
        - Series.available_list.each do |series|
          li
            = link_to series.name, series_path(series)
    
- if current_user.race_classes.empty?
  .alert.alert-warning
    |You aren't currently signed up for any series
- else
  .row.tabpanel
    .col-md-4.col-sm-4
      h4.cardHeader
        |Race Cards
      ul.nav.nav-sidebar.drop_shadow
        - current_user.race_classes.each do |race_class|
          
          li
            a data-toggle='tab' href=("#race_class#{race_class.id}")
              = race_class.series
              | &nbsp;
              = race_class.name

    .tab-content.col-md-8.col-sm-8.col-xs-12
      - current_user.race_classes.each do |race_class|
        
        .tab-pane id=("race_class#{race_class.id}") role="tabpanel"
          = render partial: 'users/race_class', locals: {series: race_class.series, race_class: race_class, round: nil}

br
.modal.fade id="bonusModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
  .modal-dialog
    .modal-content
      .modal-header
        button type="button" class="close" data-dismiss="modal" aria-hidden="true"
          | &times;
        h4.modal-title
          |Bonus Help
      .modal-body
        h3 BONUS SCORING
        b Pole Position
        ul
          li Pole Position is awarded to the fastest qualifier in timed practice.
          li If your selected racer is the winner of this category you will gain 5 points
          li If you chose a racer that didn’t win this category, yup you guessed it, you lose 5 points
        b Heat Winner
        ul
          li This is where you will choose 1 racer that you think will win the heat race he is racing in, regardless of the racer being in the first or second heat race in Supercross.
          li In Motocross, you will choose 1 racer that you think will win one of the two motos that race day. 
          li If your selection is the winner, you earn 15 points
          li If you chose wrong, your points drop by 15
        b Main Event Hole Shot
        ul
          li This is where you choose 1 racer that you think will pull the hole shot in the main event in Supercross
          li In Motocross, you will choose 1 racer that you think will pull the hole shot in one of the two motos that race day. 
          li If your rider pulls the main event holeshot, you get 20 points
          li If your rider doesn’t cross the holeshot line first, you will be deducted 20 points      
      .modal-footer
        button.btn.btn-primary type="button" data-dismiss="modal"
          |Close                              