config/routes.rb
MotoDynasty::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  root 'home#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users, only: [:show] do 
    collection { post :sort_rider }
  end
  
  resources :series

  resources :rounds, only: [:show,:index] do
    resources :licenses, only: [:new, :create, :update, :destroy]
  end

  resources :race_classes, only: [:show] do
    resources :licenses, only: [:new, :create, :update, :destroy]
  end

  resources :user_round_bonus_selections, only: [:create, :update, :destroy]

  resources :teams

  resources :rider_positions, only: [:create, :update, :destroy]

  resources :user_messages, only: [:new, :create]

  resources :custom_series_licenses, only: [:create, :destroy] do
    collection do 
      get :join
      post :accept_request
      delete :leave_custom_series
    end
  end

  resources :custom_series_invitations, only: [:create, :destroy]
  resources :custom_series_requests, only: [:create, :destroy]

  resources :custom_series do
    get :show_request    
    collection do
      get 'new_public'
      get 'new_private'
      post 'search'
    end
  end


  post '/update-with-last-week-riders', to: 'rider_positions#update_with_lastweek_riders', as: 'update_with_lastweek_riders'
  get '/instructions', to: 'home#instructions'  
  get '/series-invitation/:series_id', to: 'custom_series_invitations#new', as: 'new_series_invitation'
  # /leaderboards(/series/:series_id(/race_classes/:race_class_id(/rounds/:round_id)))
  get '/leaderboards', to: 'leaderboards/base#show', as: 'leaderboards'

  get '/manage_rounds', to: 'rounds#manage_rounds'


  namespace :leaderboards do
    resources :series, only: [:show] do
      resources :race_classes, only: [:show] do
        resources :rounds, only: [:show]
      end
    end
  end
end

app/views/shared/_flash.html.slim
- if flash[:error]
  = content_tag :div, class: "alert alert-danger alert-dismissable" do
    button.close aria-hidden="true" data-dismiss="alert" type="button" &times;
    = flash[:error]
- if flash[:notice]
  = content_tag :div, class: "alert alert-success alert-dismissable" do
    button.close aria-hidden="true" data-dismiss="alert" type="button" &times;
    = flash[:notice]
- if flash[:alert]
  = content_tag :div, class: "alert alert-info alert-dismissable" do
    button.close aria-hidden="true" data-dismiss="alert" type="button" &times;
    = flash[:alert]

app/views/shared/_footer.html.slim
footer.footer.clearfix
  .row
    .col-md-3
      h4 Contact Us
      = link_to "Send us a message", new_user_message_path
    .col-md-3
      h4 How to Play
      = link_to "Instructions", instructions_path
        / .col-md-4
          / h5 Links
          / ul.list-unstyled
          /   li
          /     | Coming Soon
  .authorship
      span © 2014 MotoDynasty. All rights reserved   

app/views/shared/_nav.html.slim
/loldiv.navbar-network.hidden-xs role="navigation"
/  nav.container
/    ul.list-unstyled
/      li
/        =image_tag 'icon-inactive.png'
/       = link_to "Vurbmoto", "http://vurbmoto.com/"
/      li
/        =image_tag 'icon-inactive.png'
/        = link_to "Shop", "http://shop.vurb.io/"
/      li.active
/        =image_tag 'MotoDynasty_Icon_Active-1.png'
/        = link_to "MotoDynasty", root_url
nav.nav.nav_header
  div
    <a class="header_link open_nav i_nav" title="Navigation">
  div.logo
    = link_to root_path, class: "motoD" do
        =image_tag 'racer-x-shield.png', alt: "racerX", class: "" 
  = link_to root_path, class: "" do
    =image_tag 'mxdy-logo.png', alt: "Motodynasty", class: "mxdyLogoMobile"
nav.nav.nav_main
  .container
    div.logo
      = link_to root_path, class: "motoD" do
        =image_tag 'racer-x-shield.png', alt: "Motodynasty", class: ""
    ul.nav_left
      = link_to root_path, class: "" do
        =image_tag 'mxdy-logo.png', alt: "Motodynasty", class: "mxdyLogo"
    ul.nav_right
      -if user_signed_in?
        li class="parent #{nav_class_for(:profile)}"
          = link_to "Play", user_path(current_user)
        li class="parent #{nav_class_for(:leaderboards)}"
          = link_to "Leaderboard", leaderboards_path
        li class="parent #{nav_class_for(:rounds)}"
          = link_to "My Results", rounds_path
        li class="parent #{nav_class_for(:custom_series)}"
          = link_to "My Series", custom_series_index_path
        li.sep
        li
          <a class="i i_facebook" target="blank" href="https://www.facebook.com/motodynastygame">
        li
          <a class="i i_twitter" target="blank" href="https://twitter.com/MotoDynasty">
        li
          <a class="i i_instagram" target="blank" href="http://instagram.com/motodynasty">
        li.sep
        li.parent
          =link_to "", edit_user_registration_path(current_user), class: "i i_user"
          .dropdown.account
            ul.sub_nav
              li
                = link_to "Settings", edit_user_registration_path(current_user)
              li
                = link_to "Sign out", destroy_user_session_path, method: :delete, id: "sign_out_link"
      - else
        li class="parent #{nav_class_for(:how_to_play)}"
          = link_to "How to Play", instructions_path
        li.sep
        li
          <a class="i i_facebook" target="blank" href="https://www.facebook.com/motodynastygame">
        li
          <a class="i i_twitter" target="blank" href="https://twitter.com/MotoDynasty">
        li
          <a class="i i_instagram" target="blank" href="http://instagram.com/motodynasty">  
        li.sep
        li.parent
          =link_to "" , new_user_session_path, class: "i i_user"
          div.dropdown.account
            ul.sub_nav
              li
                =link_to "Sign In", new_user_session_path
              li
                = link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)
              li
                = link_to "Sign up", new_user_registration_path
-if current_user
  .userBar role="navigation"
    nav.container
      ul.list-unstyled
        li.pull-left.user
          = current_user.handle
        li.pull-right.user
          = current_user.total_points
          |PTS

app/views/shared/_news.html.slim
.headlines
  .wrapper.wrapper-light
    .container
      .row
        .col-md-12
          button.btn.btn-default.headlines-more.pull-left type="button"
            i.icon-bullhorn
            | News
          ul.list-unstyled.headlines-compact
            li
              a href="/news/oak-hill-final-countdown-begins/16457/" Oak Hill Final Countdown Begins
            li
              a href="/news/rockstar-energy-ktm-uses-ride-engineering/16456/" Rockstar Energy KTM uses Ride Engineering
            li
              a href="/news/villopoto-looking-edge-a3/16455/" Villopoto Looking for an Edge at A3
      .row.headlines-extended
        .col-md-4
          ul
            li.date Today
            li
              a href="/news/oak-hill-final-countdown-begins/16457/" Oak Hill Final Countdown Begins
            li
              a href="/news/rockstar-energy-ktm-uses-ride-engineering/16456/" Rockstar Energy KTM uses Ride Engineering
            li
              a href="/news/villopoto-looking-edge-a3/16455/" Villopoto Looking for an Edge at A3
            li
              a href="/news/road-supercross-competitors-shine/16454/" Road to Supercross Competitors Shine
            li
              a href="/news/wharton-showing-military-appreciation/16453/" Wharton showing Military Appreciation
            li
              a href="/news/sipes-watts-ramirez-tonight-seat-time/16448/" Sipes, Watts, Ramirez tonight on Seat Time
            li
              a href="/news/wilvo-forkrent-ktm-sign-hawkstone/16444/" Wilvo Forkrent KTM sign up for Hawkstone
        .col-md-4
          ul
            li.date Yesterday
            li
              a href="/news/bel-rays-jason-anderson-wins-again/16443/" Bel-Ray’s Jason Anderson Wins Again
            li
              a href="/news/spring-classic-warm/16442/" Spring Classic Warm Up
            li
              a href="/news/honda-gains-valuable-points-oakland/16441/" Honda Gains Valuable Points in Oakland
            li
              a href="/news/oakhill-raceway-prepares-warm-/16440/" Oakhill Raceway Prepares for Warm-Up
            li
              a href="/news/dunlop-announces-elite-team-dunlop-squad/16435/" Dunlop Announces Elite Team Dunlop Squad
            li
              a href="/news/scott-sx-athletes-round-4/16433/" SCOTT SX Athletes at Round 4
            li
              a href="/news/tld-honda-stays-alive-oakland/16432/" TLD Honda Stays Alive in Oakland
        .col-md-4
          ul
            li
              a href="/news/nc-indoor-mx-championships/16431/" NC Indoor MX Championships
            li
              a href="/news/kawasakis-villopoto-wins-oakland/16430/" Kawasaki’s Villopoto Wins in Oakland
            li
              a href="/news/progress-geico-hondas-hahn-osborne/16429/" Progress for GEICO Hondas Hahn, Osborne
            li
              a href="/news/jacob-hayes-takes-first-career-ax-win/16428/" Jacob Hayes Takes First Career AX Win
            li
              a href="/news/round-4-texas-winter-series/16427/" Round 4 of the Texas Winter Series
            li
              a href="/news/ferris-earns-10th-overall-oakland/16426/" Ferris Earns 10th Overall at Oakland
            li
              a href="/news/dungey-earns-4th-oakland/16425/" Dungey Earns 4th at Oakland