config/routes.rb
MotoDynasty::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  root 'home#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users, only: [:show] do 
    collection { post :sort_rider }
  end
  
  resources :series

  resources :rounds, only: [:show,:index] do
    resources :licenses, only: [:new, :create, :update, :destroy]
  end

  resources :race_classes, only: [:show] do
    resources :licenses, only: [:new, :create, :update, :destroy]
  end

  resources :user_round_bonus_selections, only: [:create, :update, :destroy]

  resources :teams

  resources :rider_positions, only: [:create, :update, :destroy]

  resources :user_messages, only: [:new, :create]

  resources :custom_series_licenses, only: [:create, :destroy] do
    collection do 
      get :join
      post :accept_request
      delete :leave_custom_series
    end
  end

  resources :custom_series_invitations, only: [:create, :destroy]
  resources :custom_series_requests, only: [:create, :destroy]

  resources :custom_series do
    get :show_request    
    collection do
      get 'new_public'
      get 'new_private'
      post 'search'
    end
  end


  post '/update-with-last-week-riders', to: 'rider_positions#update_with_lastweek_riders', as: 'update_with_lastweek_riders'
  get '/instructions', to: 'home#instructions'  
  get '/series-invitation/:series_id', to: 'custom_series_invitations#new', as: 'new_series_invitation'
  # /leaderboards(/series/:series_id(/race_classes/:race_class_id(/rounds/:round_id)))
  get '/leaderboards', to: 'leaderboards/base#show', as: 'leaderboards'

  get '/manage_rounds', to: 'rounds#manage_rounds'


  namespace :leaderboards do
    resources :series, only: [:show] do
      resources :race_classes, only: [:show] do
        resources :rounds, only: [:show]
      end
    end
  end
end

app/controllers/custom_series_controller.rb
class CustomSeriesController < ApplicationController
  respond_to :json

  def index
    @private_custom_series = current_user.custom_series.private_list
    @public_custom_series = current_user.custom_series.public_list
  end

  def show
    @custom_series = CustomSeries.find(params[:id])    
    @invite = CustomSeriesInvitation.for_token_and_email(params[:token], current_user.email)    
  rescue CustomSeriesInvitation::EmailMismatchError
    @email_mismatch_error = true
  rescue ActiveRecord::RecordNotFound
    @token_error = true
  end

  def show_request
    @custom_series = CustomSeries.find(params[:custom_series_id])
    @request = CustomSeriesRequest.find_by_token(params[:request_token])
  rescue CustomSeriesInvitation::EmailMismatchError
    @email_mismatch_error = true
  rescue ActiveRecord::RecordNotFound
    @token_error = true
  end

  def new_private
    @new_private_custom_series = CustomSeries.new
    @new_private_custom_series.is_public = false
  end

  def new_public
    @new_public_custom_series = CustomSeries.new
    @new_public_custom_series.is_public = true
  end

  def create
    custom_series = current_user.owned_series.build(custom_series_params)
    if custom_series.save
      custom_series.custom_series_licenses.create(user: current_user)
      flash[:notice] = "Private Series successfully created."
      redirect_to :back
    else 
      flash[:error] = "Private Series failed to be created because #{custom_series.errors.messages}"
      redirect_to :back 
    end
  end
  
  def edit
    @custom_series = current_user.custom_series.find(params[:id])
  end

  def update
    @custom_series = CustomSeries.find(params[:id])
    @custom_series.update_attributes(custom_series_params)
    flash[:notice] = 'The series has been updated successfully.'
    redirect_to action: 'index'
  end

  def destroy
    @custom_series = current_user.custom_series.find(params[:id])
    @custom_series.destroy
    flash[:notice] = 'The series has been deleted successfully.'
    redirect_to action: 'index'
  end

  def search    
    @custom_series_list = CustomSeries.where.not(user_id: current_user.id).where("name like ?", "%#{params[:keyword]}%").limit(40)
  end
  
private 
  
  def custom_series_params
    params.require(:custom_series).permit(:name, :series_id, :is_public)
  end
end

app/helpers/custom_series_helper.rb
module CustomSeriesHelper
end

app/views/custom_series/_form.html.slim
.panel.panel-default
  .panel-heading
    h4.panel-title
      | Series Information
  .panel-body  
    = form_for @custom_series, html: { class: 'form-inline new-custom-series-form'} do |f|      
      .form-group
        = f.label :name, "Private Series Name", class: "sr-only"
        = f.text_field :name, placeholder: "Name", class: "form-control"
      .form-group
        = f.label :series_id, "Select a series", class: "sr-only"
        = f.collection_select :series_id, Series.all, :id, :name, {}, {class: 'form-control'}
      .form-group
        = f.label :is_public, "Select private/public option", class: "sr-only"
        = f.select :is_public, [['Public', true], ['Private', false]], class: 'form-control'
      = f.button "Update", class: "btn btn-default"

app/views/custom_series/_form_private.html.slim
.panel.panel-default
  .panel-heading
    h4.panel-title
      |New Private Series
  .panel-body  
    = form_for @new_private_custom_series, html: { class: 'form-inline new-custom-series-form'} do |f|
      = f.hidden_field :is_public
      .form-group
        = f.label :name, "Private Series Name", class: "sr-only"
        = f.text_field :name, placeholder: "Name", class: "form-control"
      .form-group
        = f.label :series_id, "Select a series", class: "sr-only"
        = f.collection_select :series_id, Series.available_list, :id, :name, {}, {class: 'form-control'}
      = f.button "Create", class: "btn btn-default"

app/views/custom_series/_form_public.html.slim
.panel.panel-default
  .panel-heading
    h4.panel-title
      |New Public Series
  .panel-body  
    = form_for @new_public_custom_series, html: { class: 'form-inline new-custom-series-form'} do |f|
      = f.hidden_field :is_public
      .form-group
        = f.label :name, "Private Series Name", class: "sr-only"
        = f.text_field :name, placeholder: "Name", class: "form-control"
      .form-group
        = f.label :series_id, "Select a series", class: "sr-only"
        = f.collection_select :series_id, Series.available_list, :id, :name, {}, {class: 'form-control'}
      = f.button "Create", class: "btn btn-default"

app/views/custom_series/_search_form.html.slim
= form_for CustomSeries.new, url: search_custom_series_index_path, remote: true, html: { class: 'form-inline new-custom-series-form'} do |f|      
  .form-group
    = label :keyword, "Private Series Name", class: "sr-only"
    = text_field_tag :keyword, '', placeholder: "Search Keyword", class: "form-control"
  .form-group
    = f.submit 'Search', class: 'btn i_search'

app/views/custom_series/_search_form_result.html.slim
table.table.table-striped    
  thead
    tr
      th Custom Series
      th Owner   
      td Users   
      th Actions
  tbody
    - @custom_series_list.each do |custom_series|
      tr
        td 
          = custom_series.name
        td
          = "#{custom_series.owner.name} #{custom_series.owner.email}"
        td
          = custom_series.users.count
        td
          - if custom_series.is_public
            = link_to 'Join', join_custom_series_licenses_path(user_id: current_user.id, custom_series_id: custom_series.id), class: 'btn'
          -else
            = form_for CustomSeriesRequest.new, remote: true do |f|
              = hidden_field_tag :custom_series_id, custom_series.id
              = f.submit 'Request to Join', class: 'btn'

app/views/custom_series/_token_error.html.slim
p
  |Your invite token is invalid.

app/views/custom_series/edit.html.slim
h3.series-h3
  | Edit Series @custom_series.name

= render 'form' if @custom_series.owner == current_user
= render 'custom_series_licenses'
= render 'pending_users'

app/views/custom_series/index.html.slim
.panel.panel-default
  .panel-heading
    h4.panel-title
      | Search Other Custom Series
  .panel-body  
    = render 'search_form'      
    #search_custom_series


h3.series-h3
  | My Private Series
  .pull-right
    = link_to 'Create Private Series'.html_safe, new_private_custom_series_index_path, remote: true, class: "btn i_plus add-series"

#new_private_custom_series.text-center
  
.custom-series-list.text-center

  table.table.table-striped    
    thead
      tr
        th Name
        th Series
        th Users
        th Invitations
        th Requests
        th Actions
    tbody
    - if @private_custom_series.any?       
      - @private_custom_series.each do |custom_series|
        tr
          td 
            = custom_series.name
          td
            = custom_series.series.name
          td 
            = custom_series.users.count
          td 
            = custom_series.custom_series_invitations.count
          td 
            = custom_series.custom_series_requests.count
          td
            = link_to 'Edit', edit_custom_series_path(custom_series), class: 'btn i_edit' if custom_series.owner == current_user
            = link_to 'View', custom_series_path(custom_series), class: 'btn' unless custom_series.owner == current_user
            = link_to 'Delete', custom_series_path(custom_series), method: :delete, class: 'btn i_delete', confirm: 'Are you sure?' if custom_series.owner == current_user

            = link_to 'Leave', leave_custom_series_custom_series_licenses_path(custom_series_id: custom_series.id), method: :delete, class: 'btn i_delete', confirm: 'Are you sure?' unless custom_series.owner == current_user

            = link_to 'Invite', new_series_invitation_path(custom_series.id), remote: true, class: 'btn i_share' if custom_series.owner == current_user || custom_series.includes_user?(current_user)            
            = link_to 'Share', '#', class: 'btn i_facebook'
            = link_to 'Leader Board', '#', class: 'btn'
        tr.new-series-invitation[id="new_series_invitation_#{custom_series.id}"]
h3.series-h3
  | My Public Series
  .pull-right
    = link_to 'Create Public Series'.html_safe, new_public_custom_series_index_path, remote: true, class: "btn i_plus add-series"
#new_public_custom_series.text-center
.public-custom-series-list.text-center
  table.table.table-striped    
    thead
      tr
        th Name
        th Series
        th Users
        th Invitations
        th Actions
    tbody
    - if @public_custom_series.any?       
      - @public_custom_series.each do |custom_series|
        tr
          td 
            = custom_series.name
          td
            = custom_series.series.name
          td 
            = custom_series.users.count
          td 
            = custom_series.custom_series_invitations.count
          td
            = link_to 'Edit', edit_custom_series_path(custom_series), class: 'btn i_edit' if custom_series.owner == current_user
            = link_to 'View', custom_series_path(custom_series), class: 'btn' unless custom_series.owner == current_user

            - if custom_series.owner == current_user
              = link_to 'Delete', custom_series_path(custom_series), method: :delete, class: 'btn i_delete', confirm: 'Are you sure?' 
            - else
              = link_to 'Leave', leave_custom_series_custom_series_licenses_path(custom_series_id: custom_series.id), method: :delete, class: 'btn i_delete', confirm: 'Are you sure?'

            = link_to 'Invite', new_series_invitation_path(custom_series.id), remote: true, class: 'btn i_share'
            = link_to 'Share', '#', class: 'btn i_facebook'
            = link_to 'Leader Board', '#', class: 'btn'
        tr.new-series-invitation[id="new_series_invitation_#{custom_series.id}"]


h3.series-h3
  | Custom Series Invited
.invited-list.text-center
  table.table.table-striped    
    thead
      tr
        th Custom Series
        th Master Series        
        th Sender
        th Actions
    tbody
      - current_user.get_custom_series_invitations.each do |custom_series_invitation|
        tr
          td
            = custom_series_invitation.custom_series.name
          td          
            = custom_series_invitation.custom_series.series.name
          td
            = "#{custom_series_invitation.sender.email} #{custom_series_invitation.sender.name}"
          td
            = link_to 'Accept', custom_series_path(custom_series_invitation.custom_series, token: custom_series_invitation.token), class: 'btn'

h3.series-h3
  | Requests for Your Custom Series
.invited-list.text-center
  table.table.table-striped    
    thead
      tr
        th Custom Series        
        th Sender
        th Actions
    tbody
      - current_user.get_custom_series_requests.each do |custom_series_request|
        tr
          td
            = custom_series_request.custom_series.name          
          td
            = "#{custom_series_request.sender.email} #{custom_series_request.sender.name}"
          td
            = link_to 'Detail', custom_series_show_request_path(custom_series_request.custom_series, request_token: custom_series_request.token), class: 'btn'            

app/views/custom_series/index1.html.slim
h3.series-h3
  | Private Series
  .pull-right
    = link_to '<i class="fa fa-plus"></i> Create Private Series'.html_safe, new_custom_series_path, remote: true, class: "btn btn-primary add-series"

.new_custom_series.text-center

- if @custom_series.any? 
  - @custom_series.each do |custom_series|
    .panel.panel-default
      .panel-heading
        h3.panel-title
          = custom_series.name
          .pull-right
            = link_to "Invite User", "#", class: "btn btn-success btn-xs add_user", data: { toggle: 'button', "custom-series" => custom_series.id }
      .panel-body
        .list-group.series_users
          .list-group-item.add_user_form data-custom-series=custom_series.id
            .row
              .col-md-12.text-center.invite_by_textfield
                h3 Enter user email
                span 
                  = form_for CustomSeriesInvitation.new, html: { class: 'form-inline'} do |f|
                    .form-group
                      =f.hidden_field :custom_series_id, value: custom_series.id
                      =f.label :recipient_email, class: 'sr-only'
                      =f.text_field :recipient_email, placeholder: "Email", class: 'form-control'
                    .form-group
                      =f.button "Send", class: 'btn btn-default'
          .list-group-item
              strong
                |Users
          - custom_series.custom_series_licenses.each do |license|
            .list-group-item
              = license.user.email
              -if can? :destroy, license
                .pull-right
                  =link_to "Remove", custom_series_license_path(license), method: :delete, class: "btn btn-danger btn-xs"
        - if custom_series.custom_series_invitations.any?
          .list-group.pending_invites
            .list-group-item
              strong
                |Pending invites
            - custom_series.custom_series_invitations.each do |invite|
              .list-group-item
                = invite.recipient_email
                -if can? :destroy, invite
                  .pull-right
                    =link_to "Remove", custom_series_invitation_path(invite), method: :delete, class: "btn btn-danger btn-xs"
-else
  h3
    |You do not currently have any private series.
              
div.alert.alert-danger.text-center Coming Soon!

app/views/custom_series/new_private.js.erb
if($('#new_private_custom_series').html() != ''){
  $("#new_private_custom_series").html('');
}else{
  $("#new_private_custom_series").html('<%= j render partial: "custom_series/form_private" %>');  
}

app/views/custom_series/new_public.js.erb
if($('#new_public_custom_series').html() != ''){
  $("#new_public_custom_series").html('');
}else{
  $("#new_public_custom_series").html('<%= j render partial: "custom_series/form_public" %>');
}

app/views/custom_series/search.js.erb
$("#search_custom_series").html('<%= j render partial: "custom_series/search_form_result" %>');

app/views/custom_series/show.html.slim
- if @invite
  - if @email_mismatch_error
    = render 'email_mismatch_error'
  - elsif @token_error
    = render 'token_error'
  - else
    -if @custom_series.includes_user?(current_user)
      p
        |You are already registered for this series
    -else
      - if @custom_series.is_public
        = form_for CustomSeriesLicense.new, html: { class: 'form-inline'} do |f|
          = hidden_field_tag :custom_series_invitation_id, @invite.id
          =f.hidden_field :custom_series_id, value: @custom_series.id
          =f.button "Click here to join this public series", class: 'btn btn-primary'
          =link_to "Decline", custom_series_invitation_path(@invite), method: :delete,
                   class: 'btn btn-danger btn-decline-series'
      -else
        = form_for CustomSeriesLicense.new, html: { class: 'form-inline'} do |f|
          = hidden_field_tag :custom_series_invitation_id, @invite.id
          =f.hidden_field :custom_series_id, value: @custom_series.id
          =f.button "Click here to join this private series", class: 'btn btn-primary'
          =link_to "Decline", custom_series_invitation_path(@invite), method: :delete,
                   class: 'btn btn-danger btn-decline-series'
.panel.panel-default
  .panel-heading
    h3.panel-title
      = @custom_series.name
  .panel-body
    .list-group
      .list-group-item
          strong
            |Series
      .list-group-item
        = @custom_series.series.name
      .list-group-item
          strong
            |Users
      - @custom_series.users.each do |user|
        .list-group-item
          = user.email
              

app/views/custom_series/show_request.html.slim
- if @token_error
  = render 'token_error'
- else
  -if @custom_series.includes_user?(@request.sender)
    p
      |He is already registered for this series
  -else    
    = form_for CustomSeriesLicense.new, url: accept_request_custom_series_licenses_path, html: { class: 'form-inline'} do |f|
      = hidden_field_tag :custom_series_request_id, @request.id
      =f.hidden_field :custom_series_id, value: @custom_series.id
      =f.button "Accept Request", class: 'btn btn-primary'
      =link_to "Decline", custom_series_request_path(@request), method: :delete,
               class: 'btn btn-danger btn-decline-series'

.panel.panel-default
  .panel-heading
    h3.panel-title
      | Request Sender Information
  .panel-body
    .list-group
      .list-group-item
        strong
          = "#{@request.sender.name} #{@request.sender.email}"
      

.panel.panel-default
  .panel-heading
    h3.panel-title
      = @custom_series.name
  .panel-body
    .list-group
      .list-group-item
          strong
            |Series
      .list-group-item
        = @custom_series.series.name
      .list-group-item
          strong
            |Users
      - @custom_series.users.each do |user|
        .list-group-item
          = user.email
              