config/routes.rb
MotoDynasty::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  root 'home#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users, only: [:show] do 
    collection { post :sort_rider }
  end
  
  resources :series

  resources :rounds, only: [:show,:index] do
    resources :licenses, only: [:new, :create, :update, :destroy]
  end

  resources :race_classes, only: [:show] do
    resources :licenses, only: [:new, :create, :update, :destroy]
  end

  resources :user_round_bonus_selections, only: [:create, :update, :destroy]

  resources :teams

  resources :rider_positions, only: [:create, :update, :destroy]

  resources :user_messages, only: [:new, :create]

  resources :custom_series_licenses, only: [:create, :destroy] do
    collection do 
      get :join
      post :accept_request
      delete :leave_custom_series
    end
  end

  resources :custom_series_invitations, only: [:create, :destroy]
  resources :custom_series_requests, only: [:create, :destroy]

  resources :custom_series do
    get :show_request    
    collection do
      get 'new_public'
      get 'new_private'
      post 'search'
    end
  end


  post '/update-with-last-week-riders', to: 'rider_positions#update_with_lastweek_riders', as: 'update_with_lastweek_riders'
  get '/instructions', to: 'home#instructions'  
  get '/series-invitation/:series_id', to: 'custom_series_invitations#new', as: 'new_series_invitation'
  # /leaderboards(/series/:series_id(/race_classes/:race_class_id(/rounds/:round_id)))
  get '/leaderboards', to: 'leaderboards/base#show', as: 'leaderboards'

  get '/manage_rounds', to: 'rounds#manage_rounds'


  namespace :leaderboards do
    resources :series, only: [:show] do
      resources :race_classes, only: [:show] do
        resources :rounds, only: [:show]
      end
    end
  end
end

app/controllers/leaderboards/series_controller.rb
class Leaderboards::SeriesController < Leaderboards::BaseController
  private
  def series
    @series ||= params[:id] && Series.find(params[:id])
  end

  def ancestors
    [:leaderboards]
  end

  def current
    series
  end

  def siblings
    Series.all
  end

  def children
    series.race_classes
  end

  def class_list
    series.race_classes
  end
  def series_name
    series.name
  end

  def canonical_path(options = {})
    leaderboards_series_path series, options
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  load_and_authorize_resource
  
  def index
  end

  def show
    @race_classes = @series.race_classes
  end
end

app/helpers/series_helper.rb
module SeriesHelper
  
end

app/views/series/index.html.slim
.page-header
 h1 
  |My Results 
- current_user.race_classes.each do |race_class|
  h3
    = race_class.series
    | &nbsp;
    = race_class.name
  ul.finished_rounds    
    - Round.finished_for(race_class).each do |round|
      li 
        = link_to round.name, round_path(round)

app/views/series/show.html.slim
h1 
  = @series.name
hr
p
  = link_to "Back", :back, class: 'btn btn-warning' 
  = link_to 'Leaderboard', leaderboards_series_url(@series), class: 'btn btn-info'

.clearfix
hr        
h3.series-h3
  |Race Classes
hr
.row
  - @race_classes.each do |race_class|
    .col-md-6
      h4.race-class
        = race_class.name
      - unless race_class.registered_and_paid?(current_user) || race_class.finished
        h5.race-class
        - if race_class.unpaid_license?(current_user)
          - if race_class.available_for_purchase?
            = link_to "Upgrade to win race class prizes (#{format_money @series.cost})",
                      new_race_class_license_path(race_class),
                      class: 'btn btn-success payButton'
        - else
          - if race_class.available_for_purchase?
            = link_to "Play for race class prizes (#{format_money @series.cost})",
                      new_race_class_license_path(race_class),
                      class: "btn btn-success payButton"
          = form_for [race_class, race_class.license_for(current_user)], class: "form-inline" do |f|
            = f.hidden_field :user_id, value: current_user.id
            = f.hidden_field :licensable_id, value: race_class.id
            = f.hidden_field :licensable_type, value: race_class.class
            = f.hidden_field :paid, value: false
            = f.submit "Play race class for free", class: 'btn btn-info', id: "series_join"
      - race_class.rounds.each do |round|
        h5.race-class
          a href=round_path(round) 
            = round